<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Models\AuditLog;

class SimpleBackup extends Command
{
    protected $signature = 'backup:simple';
    protected $description = 'Simple database backup (SQL file only)';

    public function handle()
    {
        try {
            Log::info('SimpleBackup: Starting...');
            $this->info('🚀 Starting backup...');

            // Check database connection
            try {
                DB::connection()->getPdo();
                Log::info('SimpleBackup: Database connected');
            } catch (\Exception $e) {
                Log::error('SimpleBackup: Database connection failed - ' . $e->getMessage());
                $this->error('❌ Database connection failed: ' . $e->getMessage());
                return Command::FAILURE;
            }

            $dbName = env('DB_DATABASE');
            Log::info("SimpleBackup: Database name: {$dbName}");
            $this->info("📦 Database: {$dbName}");

            // Get all tables
            Log::info('SimpleBackup: Getting tables...');
            $tables = DB::select('SHOW TABLES');
            $tableKey = "Tables_in_{$dbName}";
            Log::info('SimpleBackup: Found ' . count($tables) . ' tables');

            // Start SQL dump
            $sql = "-- Backup Database: {$dbName}\n";
            $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
            $sql .= "-- Generated by: Simple Backup Command\n\n";
            $sql .= "SET FOREIGN_KEY_CHECKS=0;\n";
            $sql .= "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n\n";

            foreach ($tables as $table) {
                $tableName = $table->$tableKey;
                Log::info("SimpleBackup: Processing table: {$tableName}");
                $this->info("  ↳ Backing up: {$tableName}");

                try {
                    // Drop table
                    $sql .= "-- Table: {$tableName}\n";
                    $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n\n";

                    // Create table
                    $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`");
                    $sql .= $createTable[0]->{'Create Table'} . ";\n\n";

                    // Insert data
                    $rows = DB::table($tableName)->get();

                    if ($rows->count() > 0) {
                        $sql .= "-- Data for table: {$tableName}\n";

                        foreach ($rows as $row) {
                            $row = (array) $row;
                            $columns = implode('`, `', array_keys($row));

                            $values = array_map(function($value) {
                                if (is_null($value)) {
                                    return 'NULL';
                                }
                                return "'" . addslashes($value) . "'";
                            }, $row);

                            $sql .= "INSERT INTO `{$tableName}` (`{$columns}`) VALUES (" . implode(', ', $values) . ");\n";
                        }

                        $sql .= "\n";
                    }
                } catch (\Exception $e) {
                    Log::error("SimpleBackup: Error processing table {$tableName}: " . $e->getMessage());
                    $this->error("  ✗ Error backing up {$tableName}: " . $e->getMessage());
                    // Continue with next table
                }
            }

            $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

            // Create backup directory
            Log::info('SimpleBackup: Creating directories...');
            $backupDir = storage_path('app/backups');
            if (!file_exists($backupDir)) {
                mkdir($backupDir, 0755, true);
                Log::info('SimpleBackup: Created backups directory');
            }

            // Create temp directory
            $tempDir = storage_path('app/backup-temp');
            if (!file_exists($tempDir)) {
                mkdir($tempDir, 0755, true);
                Log::info('SimpleBackup: Created temp directory');
            }

            // Save SQL file
            $timestamp = date('Y-m-d_His');
            $sqlFilename = "SistemDispensasiSMALA_{$timestamp}.sql";
            $sqlPath = $backupDir . '/' . $sqlFilename;

            Log::info("SimpleBackup: Writing SQL to {$sqlPath}");
            file_put_contents($sqlPath, $sql);
            $this->info("💾 SQL file created: {$sqlFilename}");

            // Check if SQL file was created
            if (!file_exists($sqlPath)) {
                Log::error('SimpleBackup: SQL file was not created');
                throw new \Exception('Failed to create SQL file');
            }

            $sqlSize = filesize($sqlPath);
            $fileSizeHuman = $this->formatBytes($sqlSize);
            Log::info("SimpleBackup: SQL file size: {$sqlSize} bytes");
            $this->info("💾 SQL file created: {$sqlFilename}");
            $this->info("✅ Backup completed successfully!");
            $this->info("📊 Size: {$fileSizeHuman}");
            $this->info("📂 Location: storage/app/backups/{$sqlFilename}");

            Log::info("SimpleBackup: Backup completed. File: {$sqlFilename}, Size: {$fileSizeHuman}");
            // Log to audit (jika dipanggil via API)
            if (auth()->check()) {
                AuditLog::log(
                    'backup_create',
                    "Backup berhasil dibuat: {$sqlFilename}",
                    null,
                    null,
                    null,
                    [
                        'filename' => $sqlFilename,
                        'size' => $fileSizeHuman,
                        'tables' => count($tables),
                        'format' => 'sql',
                    ]
                );
            }

            return Command::SUCCESS;

        } catch (\Exception $e) {
            Log::error('SimpleBackup: FAILED - ' . $e->getMessage());
            Log::error('SimpleBackup: Trace - ' . $e->getTraceAsString());

            $this->error("❌ Backup failed: " . $e->getMessage());

            return Command::FAILURE;
        }
    }

    private function formatBytes($bytes, $precision = 2)
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];

        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }

        return round($bytes, $precision) . ' ' . $units[$i];
    }
}
